"""Tests for ndvi_georef.py -- THE load-bearing seam (tech-lead's standing flag). Built test-first:
every fixture's expected (lat, lon) below was derived BY HAND (independently of calling the module
under test) with a standalone calculator script and pasted in as a literal constant, with the
derivation shown step-by-step in each test's comments -- not generated by the code being tested.
That is the whole point of this file: a single sign/frame error in ndvi_georef.py must make one of
these numbers wrong, not just internally self-consistent.

Shared constants (from config/ndvi_camera.json / config/field_polygon.json, read once, not
hardcoded a second, possibly-inconsistent way):
  width=640 height=480 horizontal_fov_rad=1.1033  ->  fx=fy=(640/2)/tan(1.1033/2)=520.0058046927555,
  cx=320.0, cy=240.0 (image-center principal point, v1 assumption).
  home_lat=-35.363262 home_lon=149.165237 home_alt_m=584.0 (config/field_polygon.json).
  mount offset (body frame) = (0, 0, -0.08) m (config/ndvi_camera.json mount.mount_pose_xyz_rpy).
  camera<->body axis signs = (+1, -1, -1) (ADR-007 nadir extrinsic quat_wxyz=(0,1,0,0): "camera
  X=body+X, Y=body-Y, Z=body-Z").
"""
import math
import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "src"))

from fieldguard_planning import ndvi_georef as geo  # noqa: E402
from fieldguard_planning.coverage import CoverageCell  # noqa: E402
from fieldguard_planning.ndvi_georef import (  # noqa: E402
    CameraIntrinsics,
    NdviHeatmapGrid,
    camera_world_position,
    intersect_ground_enu,
    pixel_to_camera_ray,
    pixel_to_ground_enu,
    pixel_to_latlon,
    world_enu_to_pixel,
)
from fieldguard_planning.ros2_adapter import load_home  # noqa: E402
from fieldguard_planning.mission_waypoints import latlon_to_enu  # noqa: E402

HOME_LAT, HOME_LON, HOME_ALT = load_home()
INTR = CameraIntrinsics.from_config(width_px=640, height_px=480, horizontal_fov_rad=1.1033)
IDENTITY_Q = (0.0, 0.0, 0.0, 1.0)  # (x, y, z, w): no rotation, body axes == world axes


def yaw_quat(yaw_rad: float):
    """(x, y, z, w) for a pure yaw (rotation about world/body Z) -- standard half-angle quaternion,
    used only to BUILD test inputs, independent of anything ndvi_georef.py does with it."""
    return (0.0, 0.0, math.sin(yaw_rad / 2.0), math.cos(yaw_rad / 2.0))


class TestCameraIntrinsicsFromConfig(unittest.TestCase):
    def test_matches_hand_derivation(self):
        # fx = (640/2) / tan(1.1033/2) -- computed independently with a calculator, not by calling
        # this function a second time to "check itself".
        self.assertAlmostEqual(INTR.fx, 520.0058046927555, places=6)
        self.assertAlmostEqual(INTR.fy, 520.0058046927555, places=6)
        self.assertEqual(INTR.cx, 320.0)
        self.assertEqual(INTR.cy, 240.0)


class TestPixelToLatLonHandFixtures(unittest.TestCase):
    """The three fixtures required by the task: (1) a trivial sanity case, (2) an off-nadir pixel
    at identity orientation, (3) a NON-TRIVIAL yaw combined with an off-nadir pixel in BOTH image
    axes with DIFFERENT magnitudes -- chosen specifically so an X/Y axis swap or a flipped sign in
    the camera<->body extrinsic changes the numeric answer (see
    test_axis_or_sign_error_would_fail_fixture_3 below, which proves it)."""

    def test_fixture_1_nadir_center_pixel_at_home_maps_to_home(self):
        """Drone at local ENU (0,0,15), level (identity orientation), the exact center pixel
        (320,240) -- the optical axis points straight down. By construction this must land at
        (east=0, north=0) i.e. exactly home, regardless of the (small, pure-Z) mount offset: the
        offset only shifts camera altitude, and a straight-down ray's XY hit point doesn't depend
        on the camera's starting altitude when yaw/pitch/roll are all zero."""
        lat, lon = pixel_to_latlon(320.0, 240.0, INTR, (0.0, 0.0, 15.0), IDENTITY_Q,
                                   HOME_LAT, HOME_LON, HOME_ALT)
        self.assertAlmostEqual(lat, HOME_LAT, places=9)
        self.assertAlmostEqual(lon, HOME_LON, places=9)

    def test_fixture_2_off_nadir_pixel_identity_orientation(self):
        """Hand derivation: x_n=(u-cx)/fx=0.5, y_n=0 -> u=320+0.5*520.0058...=580.0029, v=240.
        ray_cam=(0.5,0,1) -> ray_body=(+1*0.5,-1*0,-1*1)=(0.5,0,-1) -> ray_world=ray_body (identity
        orientation). camera_pos=(0,0,15-0.08)=(0,0,14.92) (mount offset is pure -Z in body frame,
        unrotated by identity orientation). Ground intersection: t=(0-14.92)/-1=14.92;
        ground=(0+14.92*0.5, 0+14.92*0)=(7.46, 0.0). lat/lon = home + (north=0)/111320,
        home_lon + east/(111320*cos(home_lat_rad)) = (-35.363262, 149.16531917546374)."""
        u = 320.0 + 0.5 * INTR.fx
        v = 240.0
        lat, lon = pixel_to_latlon(u, v, INTR, (0.0, 0.0, 15.0), IDENTITY_Q,
                                   HOME_LAT, HOME_LON, HOME_ALT)
        self.assertAlmostEqual(lat, -35.363262, places=8)
        self.assertAlmostEqual(lon, 149.16531917546374, places=8)

    def test_fixture_3_nontrivial_yaw_plus_off_nadir_both_axes(self):
        """Hand derivation (full arithmetic, independent of the module under test):
          x_n=0.6, y_n=-0.3 -> u=320+0.6*520.0058...=632.0035, v=240-0.3*520.0058...=83.9983
          ray_cam=(0.6,-0.3,1.0)
          ray_body = (+1*0.6, -1*-0.3, -1*1.0) = (0.6, 0.3, -1.0)
          yaw=90deg quaternion (x,y,z,w)=(0,0,sin45,cos45)=(0,0,0.70710678,0.70710678) ->
          R(yaw=90) = [[0,-1,0],[1,0,0],[0,0,1]]  (standard Z-axis rotation matrix at theta=90deg)
          ray_world = R @ ray_body = (-1*0.3, 1*0.6, -1.0) = (-0.3, 0.6, -1.0)
          drone at ENU (100,50,20); mount offset body (0,0,-0.08) rotated by R(90) = (0,0,-0.08)
            (Z-only offset is unaffected by a pure yaw rotation) -> camera_pos=(100,50,19.92)
          ground intersection: t=(0-19.92)/-1.0=19.92
          ground = (100 + 19.92*-0.3, 50 + 19.92*0.6) = (100-5.976, 50+11.952) = (94.024, 61.952)
          lat = home_lat + 61.952/111320 = -35.36270547826087
          lon = home_lon + 94.024/(111320*cos(radians(home_lat))) = 149.16627271927646
        """
        u = 320.0 + 0.6 * INTR.fx
        v = 240.0 + (-0.3) * INTR.fy
        q = yaw_quat(math.radians(90.0))
        lat, lon = pixel_to_latlon(u, v, INTR, (100.0, 50.0, 20.0), q,
                                   HOME_LAT, HOME_LON, HOME_ALT)
        self.assertAlmostEqual(lat, -35.36270547826087, places=7)
        self.assertAlmostEqual(lon, 149.16627271927646, places=7)

    def test_axis_or_sign_error_would_fail_fixture_3(self):
        """Proves fixture 3 actually HAS TEETH: flip a single sign in the camera<->body extrinsic
        (Y: -1 -> +1, as if someone mis-transcribed the ADR-007 mount note) and confirm the ground
        point moves by a large, easily test-failing margin (~12m, computed by hand above as the
        'WRONG-sign ground' case: (105.976, 61.952) vs the correct (94.024, 61.952)). If this test
        ever passed with the WRONG signs, fixture 3 would be too weak to trust."""
        original_signs = geo.CAMERA_TO_BODY_SIGNS
        try:
            geo.CAMERA_TO_BODY_SIGNS = (1.0, 1.0, -1.0)  # flipped Y sign (the injected bug)
            u = 320.0 + 0.6 * INTR.fx
            v = 240.0 + (-0.3) * INTR.fy
            q = yaw_quat(math.radians(90.0))
            wrong_ground = pixel_to_ground_enu(u, v, INTR, (100.0, 50.0, 20.0), q)
        finally:
            geo.CAMERA_TO_BODY_SIGNS = original_signs  # always restore, even on assertion failure

        correct_ground = (94.024, 61.952)
        dist = math.hypot(wrong_ground[0] - correct_ground[0], wrong_ground[1] - correct_ground[1])
        self.assertGreater(dist, 5.0,
                           "a flipped camera<->body sign must move the ground point by metres, "
                           "not vanish into rounding -- otherwise this fixture couldn't catch it")
        # and: the wrong result must NOT accidentally match the correct fixture's assertion bounds.
        self.assertFalse(math.isclose(wrong_ground[0], correct_ground[0], abs_tol=0.5))


class TestGroundIntersection(unittest.TestCase):
    def test_ray_pointing_up_never_intersects(self):
        # camera above ground, ray pointing UP (+Z) -- must not "intersect" behind the camera.
        self.assertIsNone(intersect_ground_enu((0.0, 0.0, 15.0), (0.0, 0.0, 1.0)))

    def test_ray_exactly_horizontal_never_intersects(self):
        self.assertIsNone(intersect_ground_enu((0.0, 0.0, 15.0), (1.0, 0.0, 0.0)))

    def test_camera_at_or_below_ground_with_downward_ray_is_rejected(self):
        # t<=0 guard: a camera already at/under ground level looking "down" must not report a
        # forward intersection (there isn't a physically sensible one along the ray's forward half).
        self.assertIsNone(intersect_ground_enu((0.0, 0.0, 0.0), (0.0, 0.0, -1.0)))


class TestCameraWorldPosition(unittest.TestCase):
    def test_mount_offset_applied_in_body_frame_identity_orientation(self):
        pos = camera_world_position((10.0, 20.0, 15.0), IDENTITY_Q)
        self.assertAlmostEqual(pos[0], 10.0, places=9)
        self.assertAlmostEqual(pos[1], 20.0, places=9)
        self.assertAlmostEqual(pos[2], 15.0 - 0.08, places=9)

    def test_mount_offset_rotates_with_yaw(self):
        # A pure Z-body offset is invariant under any yaw (rotation about Z) -- sanity check that
        # rotate_body_to_world doesn't leak the offset into X/Y under yaw.
        pos = camera_world_position((0.0, 0.0, 15.0), yaw_quat(math.radians(37.0)))
        self.assertAlmostEqual(pos[0], 0.0, places=9)
        self.assertAlmostEqual(pos[1], 0.0, places=9)
        self.assertAlmostEqual(pos[2], 15.0 - 0.08, places=9)


class TestPixelToCameraRay(unittest.TestCase):
    def test_center_pixel_is_pure_forward(self):
        ray = pixel_to_camera_ray(INTR.cx, INTR.cy, INTR)
        self.assertAlmostEqual(ray[0], 0.0, places=9)
        self.assertAlmostEqual(ray[1], 0.0, places=9)
        self.assertAlmostEqual(ray[2], 1.0, places=9)


class TestInverseTransformRoundTrip(unittest.TestCase):
    """world_enu_to_pixel must be the true inverse of pixel_to_ground_enu (composed with the
    lat/lon step) -- complements the independent hand fixtures above, which validate the FORWARD
    direction is correct; this validates the inverse (used by NdviHeatmapGrid) agrees with it."""

    def test_round_trip_several_poses_and_pixels(self):
        cases = [
            ((0.0, 0.0, 15.0), IDENTITY_Q, 320.0, 240.0),
            ((0.0, 0.0, 15.0), IDENTITY_Q, 580.0029, 240.0),
            ((100.0, 50.0, 20.0), yaw_quat(math.radians(90.0)), 632.0035, 83.9983),
            ((30.0, 40.0, 18.0), yaw_quat(math.radians(-53.0)), 200.0, 350.0),
        ]
        for drone_pos, q, u, v in cases:
            ground = pixel_to_ground_enu(u, v, INTR, drone_pos, q)
            self.assertIsNotNone(ground)
            u2, v2 = world_enu_to_pixel((ground[0], ground[1], 0.0), drone_pos, q, INTR)
            self.assertAlmostEqual(u2, u, places=4, msg=f"pixel round-trip failed for {drone_pos},{q}")
            self.assertAlmostEqual(v2, v, places=4, msg=f"pixel round-trip failed for {drone_pos},{q}")

    def test_round_trip_through_latlon_and_back(self):
        """Full loop: pixel -> lat/lon -> ENU (mission_waypoints.latlon_to_enu, the mission-side
        transform) -> pixel (world_enu_to_pixel). Confirms the georef stitch and the mission
        planner's ENU<->geodetic math agree end to end, not just within ndvi_georef.py."""
        drone_pos = (100.0, 50.0, 20.0)
        q = yaw_quat(math.radians(90.0))
        u, v = 632.0035, 83.9983
        lat, lon = pixel_to_latlon(u, v, INTR, drone_pos, q, HOME_LAT, HOME_LON, HOME_ALT)
        e, n = latlon_to_enu(lat, lon, HOME_LAT, HOME_LON)
        u2, v2 = world_enu_to_pixel((e, n, 0.0), drone_pos, q, INTR)
        self.assertAlmostEqual(u2, u, places=3)
        self.assertAlmostEqual(v2, v, places=3)


class TestNdviHeatmapGrid(unittest.TestCase):
    def _flat_grid_image(self, value: float, h=480, w=640):
        return [[value for _ in range(w)] for _ in range(h)]

    def test_single_frame_nadir_updates_center_cells(self):
        cells = [
            CoverageCell(cell_id="c_home", i=0, j=0, cx_m=0.0, cy_m=0.0),   # under the nadir camera
            CoverageCell(cell_id="c_far", i=1, j=0, cx_m=500.0, cy_m=500.0),  # far outside the FOV
        ]
        grid = NdviHeatmapGrid(cells, INTR)
        image = self._flat_grid_image(0.5)
        n_updated = grid.accumulate_frame(image, (0.0, 0.0, 15.0), IDENTITY_Q)
        self.assertEqual(n_updated, 1)
        means = grid.mean_grid()
        self.assertAlmostEqual(means["c_home"], 0.5, places=6)
        self.assertIsNone(means["c_far"])  # never imaged -- explicit None, not silently dropped
        self.assertEqual(grid.sample_counts()["c_home"], 1)
        self.assertEqual(grid.sample_counts()["c_far"], 0)
        self.assertEqual(grid.frames_accumulated, 1)

    def test_running_mean_across_two_frames(self):
        cells = [CoverageCell(cell_id="c_home", i=0, j=0, cx_m=0.0, cy_m=0.0)]
        grid = NdviHeatmapGrid(cells, INTR)
        grid.accumulate_frame(self._flat_grid_image(0.4), (0.0, 0.0, 15.0), IDENTITY_Q)
        grid.accumulate_frame(self._flat_grid_image(0.6), (0.0, 0.0, 15.0), IDENTITY_Q)
        means = grid.mean_grid()
        self.assertAlmostEqual(means["c_home"], 0.5, places=6)
        self.assertEqual(grid.sample_counts()["c_home"], 2)
        self.assertEqual(grid.frames_accumulated, 2)


if __name__ == "__main__":
    unittest.main()
